# Deploy App
---
- name: Deploy App
  hosts: all

  tasks:
    
    # Setting up pre-install
    - name: Setting up pre-install
      apt:
        name: '{{ item }}'
        state: latest
        install_recommends: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - gnupg2
        - software-properties-common
    
    # Install Docker CE
    - name: Docker CE - add key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
        
    - name: Docker CE - add repo
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/debian stretch stable'
        state: present
        
    - name: Docker CE - install packages
      apt:
        name: '{{ item }}'
        state: latest
        install_recommends: yes
      with_items:
        - docker-ce
        - docker-compose

    # Add developer account
    - name: Add developer account
      user:
        name: developer
        password: '$6$e25JeOyd$Bdpg0JJRJ6RZbcqVY1q44a5Bwzi3vEUMFkFbMinGdSnPN6kEHo9Dei0XT653gVrhPZ6iBWMQxHndAbSHgaIfZ1'
        group: docker
        shell: /bin/bash

    # Set chown/chmod
    - name: Chown
      command: find /app/ -mindepth 1 -exec chown developer:docker {} \;

    - name: Chmod - dirs
      command: find /app/ -mindepth 1 -type d -exec chmod 0775 {} \;

    - name: Chmod - files
      command: find /app/ -mindepth 1 -type f -exec chmod 0664 {} \;

    # Start App
    - name: Start App
      docker_service:
        project_src: /app/itm/content/docker
