# Deploy Mysql
---
- name: Deploy Mysql
  hosts: all

  tasks:
    
    # Setup MySQL DB
    - name: MySQL - install packages
      apt:
        name: '{{ item }}'
        state: latest
        install_recommends: yes
      with_items:
        - mysql-server
        - python-mysqldb
        
    - name: MySQL - remove test database
      mysql_db:
        name: test
        state: absent
    
    - name: MySQL - remove anonymous users
      mysql_user:
        name: ''
        host_all: yes
        state: absent
    
    - name: MySQL - remove unnecessary root
      mysql_user:
        name: 'root'
        host: '{{ ansible_fqdn }}'
        state: absent
        
    - name: MySQL - add wordpress database
      mysql_db:
        name: wordpress
        state: present
        
    - name: MySQL - add wordpress account
      mysql_user:
        name: 'wordpress'
        password: 'password'
        priv: 'wordpress.*:ALL'
        state: present
        
    - name: MySQL - add developer account
      mysql_user:
        name: 'developer'
        password: 'password'
        priv: 'wordpress.*:ALL'
        state: present

    - name: MySQL - stop service
      service:
        name: mysql
        state: stopped

    - name: MySQL - disable service
      service:
        name: mysql
        enabled: no

    - name: MySQL - copy database
      synchronize:
        src: /var/lib/mysql/
        dest: /app/mysql/
        owner: no
        group: no
        perms: no
      delegate_to: "{{ inventory_hostname }}"

    - name: MySQL - set owners
      command: find /app/mysql/ -mindepth 1 -exec chown developer:docker {} \;

    - name: MySQL - set dirs permissions
      command: find /app/mysql/ -mindepth 1 -type d -exec chmod 0777 developer:docker {} \;

    - name: MySQL - set files permissions
      command: find /app/mysql/ -mindepth 1 -type f -exec chmod 0666 developer:docker {} \;
