# Deploy Wordpress
---
- name: Deploy Wordpress
  hosts: all

  tasks:
    
    # Deploy Wordpress
    - name: Wordpress - download/extract
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /var/www
        remote_src: yes
        
    - name: Wordpress - copy config
      copy:
        src: /var/www/wordpress/wp-config-sample.php
        dest: /var/www/wordpress/wp-config.php
        owner: root
        group: root
        mode: 0644
        
    - name: Wordpress - set database
      replace:
        dest: /var/www/wordpress/wp-config.php
        regexp: 'database_name_here'
        replace: 'wordpress'
        
    - name: Wordpress - set username
      replace:
        dest: /var/www/wordpress/wp-config.php
        regexp: 'username_here'
        replace: 'wordpress'
        
    - name: Wordpress - set password
      replace:
        dest: /var/www/wordpress/wp-config.php
        regexp: 'password_here'
        replace: 'password'
