# DevEnv
---
- name: DevEnv
  hosts: all

  tasks:
    
    # Install MySQL
    - name: MySQL - install package
      apt:
        name: '{{ packages }}'
        state: latest
        install_recommends: yes
      vars:
        packages:
        - mysql-server
        - python-mysqldb
        
    - name: MySQL - remove test database
      mysql_db:
        name: test
        state: absent
    
    - name: MySQL - remove anonymous users
      mysql_user:
        name: ''
        host_all: yes
        state: absent
    
    - name: MySQL - remove unnecessary root
      mysql_user:
        name: 'root'
        host: '{{ ansible_fqdn }}'
        state: absent
        
    - name: MySQL - add wordpress database
      mysql_db:
        name: wordpress
        state: present
        
    - name: MySQL - add wordpress account
      mysql_user:
        name: 'wordpress'
        password: 'password'
        priv: 'wordpress.*:ALL'
        state: present
        
    - name: MySQL - add developer account
      mysql_user:
        name: 'developer'
        password: 'password'
        priv: 'wordpress.*:ALL'
        state: present
      
    # Install PHP
    - name: PHP - install packages
      apt:
        name: '{{ packages }}'
        state: latest
        install_recommends: yes
      vars:
        packages:
        - php-fpm
        - php-mysql
        
    # Install Nginx
    - name: Nginx - install packages
      apt:
        name: '{{ packages }}'
        state: latest
        install_recommends: yes
      vars:
        packages:
        - nginx
    
    - name: Nginx - disable default site
      file:
        dest: /etc/nginx/sites-enabled/default
        state: absent        
        
    # Install Wordpress
    - name: Wordpress - download/extract
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /var/www
        remote_src: yes
        
    - name: Wordpress - copy config
      copy:
        src: /var/www/wordpress/wp-config-sample.php
        dest: /var/www/wordpress/wp-config.php
        owner: root
        group: root
        mode: 0644
        
    - name: Wordpress - set database
      replace:
        dest: /var/www/wordpress/wp-config.php
        regexp: 'database_name_here'
        replace: 'wordpress'
        
    - name: Wordpress - set username
      replace:
        dest: /var/www/wordpress/wp-config.php
        regexp: 'username_here'
        replace: 'wordpress'
        
    - name: Wordpress - set password
      replace:
        dest: /var/www/wordpress/wp-config.php
        regexp: 'password_here'
        replace: 'password'
        
    - name: Wordpress - create site
      file:
        path: "/etc/nginx/sites-available/wordpress"
        state: touch
        
    - name: Wordpress - set site
      blockinfile:
        dest: /etc/nginx/sites-available/wordpress
        block: |
          server {
            listen 80 default_server;
            listen [::]:80 default_server;
            root /var/www/wordpress;
            index index.html index.htm index.nginx-debian.html index.php;
            server_name _;
            location / {
              try_files $uri $uri/ =404;
            }
            location ~ \.php$ {
              include snippets/fastcgi-php.conf;
              fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
            }
            location ~ /\.ht {
              deny all;
            }
          }
    
    - name: Wordpress - enable site
      file:
        src: /etc/nginx/sites-available/wordpress
        dest: /etc/nginx/sites-enabled/wordpress
        state: link
    
    - name: Wordpress - Nginx restart
      service:
        name: nginx
        state: restarted
